package org.dnal.core;

public enum  ErrorType {
	PARSINGERROR,
	MISSINGFIELD,
	UNKNOWNFIELD,
	DUPLICATEFIELD,
	DUPLICATEFIELDNAME,
	NODATA, 
	WRONGTYPE,
	RULEFAIL, UNKNOWNRULE, INVALIDRULE, REFERROR
}